# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)"'
    path: $(System.DefaultWorkingDirectory)/node_modules
    restoreKeys: 'yarn | "$(Agent.OS)"'

- task: CmdLine@2
  inputs:
    script: 'npm install'

- task: CmdLine@2
  inputs:
    script: |
      env
      pwd
      ls -la
